package com.paravai.foundation.domain.event;

import com.paravai.foundation.domain.value.IdValue;
import com.paravai.foundation.domain.value.TimestampValue;

public record DomainEventMetadata(
        /**
         * Unique identifier for this specific event instance.
         */
        IdValue eventId,

        /**
         * Timestamp of when the domain event occurred.
         */
        TimestampValue occurredOn,

        /**
         * Optional version number to support event schema evolution.
         */
        int version
) {
    public static DomainEventMetadata autoGenerated() {
        return new DomainEventMetadata(IdValue.generate(), TimestampValue.now(), 1);
    }

    public static DomainEventMetadata of(IdValue id, TimestampValue timestamp, int version) {
        return new DomainEventMetadata(id, timestamp, version);
    }
}