package com.paravai.foundation.domaincore.event;

/**
 * Base class for all domain events.
 * Provides a metadata object that contains information such as event ID,
 * timestamp, and other contextual attributes.
 *
 * The metadata is automatically generated when the event is created.
 * All concrete domain events extend this class and inherit the metadata.
 */
public abstract class DomainEvent {
    private final DomainEventMetadata metadata;

    protected DomainEvent() {
        this.metadata = DomainEventMetadata.autoGenerated();
    }

    public DomainEventMetadata metadata() {
        return metadata;
    }
}